import type { Metadata } from "next";
import Link from "next/link";
import { generatePageMetadata } from "@/lib/metadata";
import { COMPANY } from "@/lib/constants";

export const metadata: Metadata = generatePageMetadata({
  title: "Privacy Policy | GreenPump Care Halifax",
  description:
    "GreenPump Care Inc. privacy policy. How we collect, use, and protect your personal information in accordance with Canadian privacy law (PIPEDA).",
  slug: "/privacy",
});

const LAST_UPDATED = "April 19, 2026";

export default function PrivacyPage() {
  return (
    <article className="py-20 lg:py-28">
      <div className="container max-w-[760px]">
        {/* Header */}
        <header className="mb-12 text-center">
          <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-primary mb-4">
            Legal
          </p>
          <h1 className="font-heading text-4xl sm:text-5xl font-semibold text-text tracking-tight mb-4">
            Privacy Policy
          </h1>
          <p className="text-gray-500 text-sm">
            Last updated: {LAST_UPDATED}
          </p>
        </header>

        {/* Intro */}
        <section className="space-y-4 text-gray-700 leading-relaxed mb-10">
          <p>
            This Privacy Policy describes our policies and procedures on the
            collection, use, and disclosure of your information when you use
            the Service and tells you about your privacy rights and how the law
            protects you.
          </p>
          <p>
            We use your Personal Data to provide and improve the Service. By
            using the Service, you agree to the collection and use of information
            in accordance with this Privacy Policy.
          </p>
        </section>

        {/* Section 1 */}
        <Section title="1. Interpretation and Definitions">
          <h3 className="font-heading text-lg font-semibold text-text mt-6 mb-3">
            Interpretation
          </h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3 className="font-heading text-lg font-semibold text-text mt-6 mb-3">
            Definitions
          </h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="space-y-3 mt-3">
            <DefItem term="Affiliate">
              means an entity that controls, is controlled by or is under common
              control with a party, where &ldquo;control&rdquo; means ownership
              of 50% or more of the shares, equity interest or other securities
              entitled to vote for election of directors or other managing
              authority.
            </DefItem>
            <DefItem term="Company">
              (referred to as either &ldquo;the Company&rdquo;, &ldquo;We&rdquo;,
              &ldquo;Us&rdquo; or &ldquo;Our&rdquo; in this Agreement) refers to
              GreenPump Care Inc., 3600 Kempt Rd 212, Halifax, NS B3K 4X8.
            </DefItem>
            <DefItem term="Cookies">
              are small files that are placed on your computer, mobile device or
              any other device by a website, containing the details of your
              browsing history on that website among its many uses.
            </DefItem>
            <DefItem term="Country">refers to: Canada</DefItem>
            <DefItem term="Device">
              means any device that can access the Service such as a computer,
              a cellphone or a digital tablet.
            </DefItem>
            <DefItem term="Personal Data">
              is any information that relates to an identified or identifiable
              individual.
            </DefItem>
            <DefItem term="Service">refers to the Website.</DefItem>
            <DefItem term="Service Provider">
              means any natural or legal person who processes the data on behalf
              of the Company. It refers to third-party companies or individuals
              employed by the Company to facilitate the Service, to provide the
              Service on behalf of the Company, to perform services related to
              the Service or to assist the Company in analyzing how the Service
              is used.
            </DefItem>
            <DefItem term="Usage Data">
              refers to data collected automatically, either generated by the
              use of the Service or from the Service infrastructure itself (for
              example, the duration of a page visit).
            </DefItem>
            <DefItem term="Website">
              refers to GreenPump Care, accessible from{" "}
              <a
                href={COMPANY.website}
                className="text-primary hover:underline"
              >
                {COMPANY.website.replace(/^https?:\/\//, "")}
              </a>
              .
            </DefItem>
            <DefItem term="You">
              means the individual accessing or using the Service, or the
              company, or other legal entity on behalf of which such individual
              is accessing or using the Service, as applicable.
            </DefItem>
          </ul>
        </Section>

        {/* Section 2 */}
        <Section title="2. Collecting and Using Your Personal Data">
          <h3 className="font-heading text-lg font-semibold text-text mt-6 mb-3">
            Types of Data Collected
          </h3>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Personal Data
          </h4>
          <p>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you. Personally identifiable information may include, but
            is not limited to:
          </p>
          <Bullets
            items={[
              "Email address",
              "First name and last name",
              "Phone number",
              "Address, State, Province, ZIP/Postal code, City",
              "Usage Data",
            ]}
          />

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Usage Data
          </h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p className="mt-3">
            Like most websites, GreenPump Care gathers Usage Data that does not
            reveal personal information, which may include information such as
            your device&apos;s Internet Protocol address (e.g. IP address),
            browser type, browser version, the pages of our Service that you
            visit, the time and date of your visit, the time spent on those
            pages, unique device identifiers, and other diagnostic data.
          </p>
          <p className="mt-3">
            When you access the Service by or through a mobile device, we may
            collect certain information automatically, including, but not
            limited to, the type of mobile device you use, your mobile device
            unique ID, the IP address of your mobile device, your mobile
            operating system, the type of mobile Internet browser you use,
            unique device identifiers, and other diagnostic data.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Tracking Technologies and Cookies
          </h4>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze our Service. The
            technologies we use may include:
          </p>
          <Bullets
            items={[
              <>
                <strong>Cookies or Browser Cookies.</strong> A cookie is a small
                file placed on your device. You can instruct your browser to
                refuse all Cookies or to indicate when a Cookie is being sent.
                However, if you do not accept Cookies, you may not be able to
                use some parts of our Service. Unless you have adjusted your
                browser setting so that it will refuse Cookies, our Service may
                use Cookies.
              </>,
              <>
                <strong>Web Beacons.</strong> Certain sections of our Service
                and our emails may contain small electronic files known as web
                beacons (also referred to as clear gifs, pixel tags, and
                single-pixel gifs) that permit the Company, for example, to
                count users who have visited those pages or opened an email and
                for other related website statistics.
              </>,
            ]}
          />
          <p className="mt-3">
            Cookies can be &ldquo;Persistent&rdquo; or &ldquo;Session&rdquo;
            Cookies. Persistent Cookies remain on your personal computer or
            mobile device when you go offline, while Session Cookies are deleted
            as soon as you close your web browser.
          </p>

          <div className="mt-5 space-y-4">
            <CookieCard
              title="Necessary / Essential Cookies"
              meta="Session Cookies · Administered by us"
              body="These Cookies are essential to provide you with services available through the Website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts."
            />
            <CookieCard
              title="Cookies Policy / Notice Acceptance Cookies"
              meta="Persistent Cookies · Administered by us"
              body="These Cookies identify if users have accepted the use of cookies on the Website."
            />
            <CookieCard
              title="Functionality Cookies"
              meta="Persistent Cookies · Administered by us"
              body="These Cookies allow us to remember choices you make when you use the Website, such as remembering your login details or language preference, to provide a more personal experience."
            />
          </div>
        </Section>

        {/* Section 3 */}
        <Section title="3. Use of Your Personal Data">
          <p>The Company may use Personal Data for the following purposes:</p>
          <Bullets
            items={[
              "To provide and maintain our Service, including to monitor the usage of our Service.",
              "To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services, including security updates when necessary or reasonable.",
              "To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those you have already purchased or enquired about, unless you have opted not to receive such information.",
              "To manage your requests: to attend and manage your requests to us.",
              "For business transfers: to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets.",
              "For other purposes: data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our Service, products, services, marketing, and your experience.",
            ]}
          />
          <p className="mt-4">
            We may share your personal information in the following situations:
          </p>
          <Bullets
            items={[
              "With Service Providers: to monitor and analyze the use of our Service, and to contact you.",
              "For business transfers: in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business.",
              "With Affiliates: we will require those affiliates to honor this Privacy Policy.",
              "With business partners: to offer you certain products, services, or promotions.",
              "With other users: when you share personal information or otherwise interact in public areas with other users.",
              "With your consent: for any other purpose with your consent.",
            ]}
          />
        </Section>

        {/* Section 4 */}
        <Section title="4. Retention of Your Personal Data">
          <p>
            The Company will retain your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy. We will
            retain and use your Personal Data to the extent necessary to comply
            with our legal obligations (for example, if we are required to
            retain your data to comply with applicable laws), resolve disputes,
            and enforce our legal agreements and policies.
          </p>
          <p className="mt-3">
            The Company will also retain Usage Data for internal analysis
            purposes. Usage Data is generally retained for a shorter period of
            time, except when this data is used to strengthen the security or
            to improve the functionality of our Service, or we are legally
            obligated to retain this data for longer time periods.
          </p>
        </Section>

        {/* Section 5 */}
        <Section title="5. Transfer of Your Personal Data">
          <p>
            Your information, including Personal Data, is processed at the
            Company&apos;s operating offices and in any other places where the
            parties involved in the processing are located. This means that
            this information may be transferred to — and maintained on —
            computers located outside of your state, province, country, or
            other governmental jurisdiction where the data protection laws may
            differ from those of your jurisdiction.
          </p>
          <p className="mt-3">
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </p>
          <p className="mt-3">
            The Company will take all steps reasonably necessary to ensure that
            your data is treated securely and in accordance with this Privacy
            Policy and no transfer of your Personal Data will take place to an
            organization or a country unless there are adequate controls in
            place, including the security of your data and other personal
            information.
          </p>
        </Section>

        {/* Section 6 */}
        <Section title="6. Delete Your Personal Data">
          <p>
            You have the right to delete or request that we assist in deleting
            the Personal Data that we have collected about you.
          </p>
          <p className="mt-3">
            Our Service may give you the ability to delete certain information
            about you from within the Service.
          </p>
          <p className="mt-3">
            You may contact us at{" "}
            <Link href="/contact" className="text-primary hover:underline">
              our contact page
            </Link>{" "}
            to request access to, correct, or delete any personal information
            that you have provided to us.
          </p>
          <p className="mt-3">
            Please note that we may need to retain certain information when we
            have a legal obligation or lawful basis to do so.
          </p>
        </Section>

        {/* Section 7 */}
        <Section title="7. Disclosure of Your Personal Data">
          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Business Transactions
          </h4>
          <p>
            If the Company is involved in a merger, acquisition, or asset sale,
            your Personal Data may be transferred. We will provide notice
            before your Personal Data is transferred and becomes subject to a
            different Privacy Policy.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Law Enforcement
          </h4>
          <p>
            Under certain circumstances, the Company may be required to
            disclose your Personal Data if required to do so by law or in
            response to valid requests by public authorities (e.g. a court or
            a government agency).
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Other Legal Requirements
          </h4>
          <p>
            The Company may disclose your Personal Data in the good faith
            belief that such action is necessary to:
          </p>
          <Bullets
            items={[
              "Comply with a legal obligation",
              "Protect and defend the rights or property of the Company",
              "Prevent or investigate possible wrongdoing in connection with the Service",
              "Protect the personal safety of users of the Service or the public",
              "Protect against legal liability",
            ]}
          />
        </Section>

        {/* Section 8 */}
        <Section title="8. Security of Your Personal Data">
          <p>
            The security of your Personal Data is important to us, but remember
            that no method of transmission over the Internet or method of
            electronic storage is 100% secure. While we strive to use
            commercially acceptable means to protect your Personal Data, we
            cannot guarantee its absolute security.
          </p>
        </Section>

        {/* Section 9 */}
        <Section title="9. Canadian Privacy Rights (PIPEDA)">
          <p>
            GreenPump Care Inc. is a Canadian company subject to the Personal
            Information Protection and Electronic Documents Act (PIPEDA),
            Canada&apos;s federal private-sector privacy law. PIPEDA sets out
            the ground rules for how businesses must handle personal
            information in the course of commercial activity.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Your Rights Under PIPEDA
          </h4>
          <p>
            As an individual whose personal information is held by GreenPump
            Care Inc., you have the right to:
          </p>
          <Bullets
            items={[
              "Know why your personal information is being collected, used, or disclosed.",
              "Expect that your personal information will be used only for the purpose for which it was collected.",
              "Access your personal information and request corrections if it is inaccurate, incomplete, or out of date.",
              "Withdraw your consent for the collection, use, or disclosure of your personal information, subject to legal or contractual restrictions and reasonable notice.",
              "Lodge a complaint with the Office of the Privacy Commissioner of Canada if you believe your privacy rights have been violated.",
            ]}
          />

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Our Obligations
          </h4>
          <p>
            GreenPump Care Inc. is committed to collecting only the personal
            information that is necessary for the identified purposes,
            obtaining meaningful consent, safeguarding the information
            entrusted to us, and being transparent about our privacy practices.
            We have appointed a Privacy Officer who is accountable for our
            compliance with PIPEDA. You may reach our Privacy Officer through
            the contact information provided in the Contact Us section of this
            policy.
          </p>
          <p className="mt-3">
            For more information about your rights under PIPEDA, visit the
            Office of the Privacy Commissioner of Canada at{" "}
            <a
              href="https://www.priv.gc.ca"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              www.priv.gc.ca
            </a>
            .
          </p>
        </Section>

        {/* Section 10 */}
        <Section title="10. SMS and Text Message Communications">
          <p>
            GreenPump Care Inc. may send you SMS (text message) communications,
            including appointment reminders, service updates, and promotional
            offers, through our SMS number (902) 710-7424. By providing your
            mobile phone number and opting in to SMS communications, you
            consent to receive text messages from us.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Consent and Opt-In
          </h4>
          <p>
            We will only send you SMS messages if you have provided explicit
            consent. Consent may be obtained through our website, over the
            phone, or through a signed service agreement. Message and data
            rates may apply.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Opting Out
          </h4>
          <p>
            You may opt out of SMS communications at any time by replying{" "}
            <strong>STOP</strong> to any text message we send you. After opting
            out, you will receive a single confirmation message and will no
            longer receive SMS communications from GreenPump Care Inc. unless
            you re-subscribe.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Help
          </h4>
          <p>
            For help regarding our SMS communications, reply{" "}
            <strong>HELP</strong> to any text message or contact us at{" "}
            <a
              href={COMPANY.phoneHref}
              className="text-primary hover:underline"
            >
              {COMPANY.phone}
            </a>{" "}
            or{" "}
            <a
              href={COMPANY.emailHref}
              className="text-primary hover:underline"
            >
              {COMPANY.email}
            </a>
            .
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Data Privacy for SMS
          </h4>
          <p>
            We do not share your mobile phone number or SMS consent data with
            third parties for marketing purposes. Your mobile information will
            not be sold, rented, or traded. SMS opt-in data and consent are not
            shared with any third party.
          </p>

          <h4 className="font-heading font-semibold text-text mt-5 mb-2">
            Types of SMS Messages
          </h4>
          <p>
            The types of SMS messages you may receive from GreenPump Care Inc.
            include, but are not limited to:
          </p>
          <Bullets
            items={[
              "Appointment confirmations and reminders",
              "Service completion notifications",
              "Maintenance reminders and seasonal check-up alerts",
              "Promotional offers and special pricing",
              "Follow-up messages regarding your service",
              "Emergency or urgent service communications",
            ]}
          />
        </Section>

        {/* Section 11 */}
        <Section title="11. Children's Privacy">
          <p>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If you are a parent or guardian and you are
            aware that your child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal
            Data from anyone under the age of 13 without verification of
            parental consent, we take steps to remove that information from
            our servers.
          </p>
          <p className="mt-3">
            If we need to rely on consent as a legal basis for processing your
            information and your country requires consent from a parent, we
            may require your parent&apos;s consent before we collect and use
            that information.
          </p>
        </Section>

        {/* Section 12 */}
        <Section title="12. Changes to this Privacy Policy">
          <p>
            We may update our Privacy Policy from time to time by posting the
            new Privacy Policy on this page. You are advised to review this
            Privacy Policy periodically for any changes. Changes to this
            Privacy Policy are effective when they are posted on this page.
          </p>
        </Section>

        {/* Section 13 */}
        <Section title="13. Contact Us" hideBorder>
          <p>
            If you have any questions about this Privacy Policy, or regarding
            anything else, you can contact us:
          </p>
          <ul className="mt-3 space-y-2">
            <li>
              By visiting our{" "}
              <Link href="/contact" className="text-primary hover:underline">
                contact page
              </Link>
              .
            </li>
            <li>
              By email:{" "}
              <a
                href={COMPANY.emailHref}
                className="text-primary hover:underline"
              >
                {COMPANY.email}
              </a>
            </li>
            <li>
              By phone:{" "}
              <a
                href={COMPANY.phoneHref}
                className="text-primary hover:underline"
              >
                {COMPANY.phone}
              </a>
            </li>
            <li>
              By mail: GreenPump Care Inc., 3600 Kempt Rd 212, Halifax, NS
              B3K 4X8
            </li>
          </ul>
        </Section>

        {/* Footer note */}
        <footer className="mt-12 pt-6 border-t border-gray-100 text-center text-xs text-gray-400">
          <p>
            GreenPump Care Inc. · 3600 Kempt Rd 212, Halifax, NS B3K 4X8
          </p>
        </footer>
      </div>
    </article>
  );
}

function Section({
  title,
  children,
  hideBorder = false,
}: {
  title: string;
  children: React.ReactNode;
  hideBorder?: boolean;
}) {
  return (
    <section
      className={`py-8 ${hideBorder ? "" : "border-b border-gray-100"}`}
    >
      <h2 className="font-heading text-2xl font-semibold text-text tracking-tight mb-4">
        {title}
      </h2>
      <div className="text-gray-700 leading-relaxed space-y-1">{children}</div>
    </section>
  );
}

function DefItem({
  term,
  children,
}: {
  term: string;
  children: React.ReactNode;
}) {
  return (
    <li className="text-gray-700">
      <strong className="text-text">{term}</strong> — {children}
    </li>
  );
}

function Bullets({ items }: { items: React.ReactNode[] }) {
  return (
    <ul className="mt-3 space-y-2 pl-5 list-disc marker:text-primary">
      {items.map((item, i) => (
        <li key={i} className="text-gray-700 leading-relaxed">
          {item}
        </li>
      ))}
    </ul>
  );
}

function CookieCard({
  title,
  meta,
  body,
}: {
  title: string;
  meta: string;
  body: string;
}) {
  return (
    <div className="bg-stripe rounded-card p-5">
      <p className="font-heading font-semibold text-text mb-1">{title}</p>
      <p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-primary mb-2">
        {meta}
      </p>
      <p className="text-gray-700 text-sm leading-relaxed">{body}</p>
    </div>
  );
}
